import type { AuditEvent, InboxMessage } from "../../lib/types";

export const demoMessages: InboxMessage[] = [
  {
    id: "msg_01J72Q6FT3",
    threadId: "thr_01J72Q4SBA",
    sender: "Maya Patel",
    initials: "MP",
    email: "maya@oakandpine.co.uk",
    company: "Oak & Pine Interiors",
    subject: "Re: Rollout timeline for 42 stores",
    preview:
      "Thanks for the walkthrough. The team would like to move forward and needs a phased rollout plan…",
    receivedAt: "9:42 AM",
    timestamp: "Today, 9:42 AM",
    unread: true,
    priority: "high",
    category: "Sales opportunity",
    secondaryCategories: ["Meeting request", "Document request"],
    sentiment: "Positive",
    status: "draft-ready",
    confidence: 94,
    relationship: "Active prospect",
    summary:
      "Oak & Pine wants to move forward with a 42-store rollout. Maya is asking for a phased implementation plan, confirmed pricing and a call next week before their Friday steering meeting.",
    intent: "Obtain proposal and schedule implementation call",
    nextAction: "Review the draft and confirm who owns the rollout estimate.",
    assignee: "Alex Morgan",
    labels: ["SALES", "HIGH VALUE", "DRAFT READY"],
    riskLevel: "none",
    riskFlags: [],
    facts: [
      "The rollout covers 42 UK stores.",
      "Their steering meeting is next Friday.",
      "Maya requested a phased plan and pricing confirmation.",
    ],
    missingInformation: ["Approved implementation lead", "Final rollout estimate"],
    extracted: [
      { label: "Account", value: "Oak & Pine Interiors", verified: true },
      { label: "Scope", value: "42 stores", verified: true },
      { label: "Target", value: "September", verified: true },
      { label: "Deadline", value: "Friday steering meeting", verified: true },
    ],
    requiredActions: [
      "Confirm implementation owner",
      "Attach approved phased rollout plan",
      "Offer two call windows next week",
    ],
    attachments: [
      {
        name: "Oak-and-Pine-rollout-brief.pdf",
        type: "PDF",
        size: "1.8 MB",
        risk: "safe",
      },
    ],
    thread: [
      {
        id: "entry_01",
        sender: "Maya Patel",
        email: "maya@oakandpine.co.uk",
        timestamp: "Today, 9:42 AM",
        direction: "inbound",
        body: [
          "Hi Alex,",
          "Thanks again for the walkthrough yesterday. The team would like to move forward and we’re now planning around a September start across all 42 UK stores.",
          "Could you send over the phased rollout plan you mentioned, confirm the pricing is still as discussed, and suggest a couple of times for an implementation call next week? We have a steering meeting next Friday, so having this beforehand would be ideal.",
          "I’ve attached the updated store brief for context.",
          "Best,\nMaya",
        ],
      },
    ],
    draft: {
      subject: "Re: Rollout timeline for 42 stores",
      body: [
        "Hi Maya,",
        "Great to hear the team is ready to move forward. I’ve noted the September target and the 42-store scope.",
        "I’m confirming the implementation owner and the latest approved rollout estimate now. I’ll send the phased plan and verified pricing before your steering meeting next Friday, together with two options for a call next week.",
        "If there are any blackout dates in September that we should account for, please send those over and I’ll include them in the plan.",
      ],
      signature: "Best,\nAlex\nNorthstar Goods",
    },
    auditReason:
      "Active prospect requested rollout documents and a meeting; full scope and deadline were stated; pricing and ownership still require verification; draft only under Safe Mode.",
  },
  {
    id: "msg_01J72PXV8M",
    threadId: "thr_01J72PTWW0",
    sender: "Daniel Reeves",
    initials: "DR",
    email: "daniel@kinshipmarket.com",
    company: "Kinship Market",
    subject: "Checkout failing after this morning’s update",
    preview:
      "We are seeing a 502 error on every checkout across three sites. Orders are currently blocked…",
    receivedAt: "9:18 AM",
    timestamp: "Today, 9:18 AM",
    unread: true,
    priority: "critical",
    category: "Technical issue",
    secondaryCategories: ["Customer support", "Service disruption"],
    sentiment: "Urgent",
    status: "escalated",
    confidence: 97,
    relationship: "Active customer",
    summary:
      "Kinship Market reports a repeatable 502 error during checkout on three production sites following this morning’s update. Orders are blocked and no workaround is known.",
    intent: "Restore checkout and obtain an incident update",
    nextAction: "Engineering incident owner should acknowledge and post a verified status update.",
    assignee: "Incident response",
    labels: ["CRITICAL", "SUPPORT", "INCIDENT"],
    riskLevel: "review",
    riskFlags: ["Production outage", "Customer revenue impact"],
    facts: [
      "Checkout returns HTTP 502.",
      "Three production sites are affected.",
      "The issue started after this morning’s update.",
    ],
    missingInformation: ["Incident ID", "Confirmed root cause", "Recovery estimate"],
    extracted: [
      { label: "Error", value: "HTTP 502", verified: true },
      { label: "Impact", value: "Orders blocked", verified: true },
      { label: "Sites", value: "3 production sites", verified: true },
      { label: "Started", value: "After morning update", verified: true },
    ],
    requiredActions: [
      "Link the incident record",
      "Confirm whether rollback is in progress",
      "Provide next verified update time",
    ],
    attachments: [
      { name: "checkout-502.png", type: "PNG", size: "428 KB", risk: "safe" },
    ],
    thread: [
      {
        id: "entry_02",
        sender: "Daniel Reeves",
        email: "daniel@kinshipmarket.com",
        timestamp: "Today, 9:18 AM",
        direction: "inbound",
        body: [
          "Hi support,",
          "We are seeing a 502 error on every checkout across our three live sites. This began after the update this morning and orders are currently blocked.",
          "Can you confirm whether there is an incident open and when we should expect the next update? A screenshot is attached.",
          "Daniel",
        ],
      },
    ],
    draft: {
      subject: "Re: Checkout failing after this morning’s update",
      body: [
        "Hi Daniel,",
        "Thanks for flagging this. I understand that checkout is returning a 502 error across all three production sites and that orders are currently blocked.",
        "The issue has been routed for urgent incident review. I can’t yet verify a root cause or recovery time. We’ll share the incident reference and next confirmed update as soon as the response owner has validated them.",
      ],
      signature: "Regards,\nNorthstar Support",
    },
    auditReason:
      "Active customer reported a production checkout outage with material impact; critical escalation required; no recovery estimate is verified; holding draft requires approval.",
  },
  {
    id: "msg_01J72P7P52",
    threadId: "thr_01J72P1XQ8",
    sender: "Accounts Team",
    initials: "HL",
    email: "accounts@halcyon-logistics.co",
    company: "Halcyon Logistics",
    subject: "Urgent: invoice HLC-8841 — new payment details",
    preview:
      "Please disregard our previous bank account and use the replacement details in the attached invoice…",
    receivedAt: "8:51 AM",
    timestamp: "Today, 8:51 AM",
    unread: true,
    priority: "critical",
    category: "Security review",
    secondaryCategories: ["Invoice received", "Payment detail change"],
    sentiment: "Urgent",
    status: "escalated",
    confidence: 99,
    relationship: "Unverified supplier",
    summary:
      "An unverified sender asks Northstar to replace previously held bank details and pay invoice HLC-8841 today. The reply-to domain differs from the known supplier domain.",
    intent: "Change payment destination and obtain same-day payment",
    nextAction: "Verify the request with the supplier through a known contact channel; do not reply or forward.",
    assignee: "Security & Finance",
    labels: ["SECURITY REVIEW", "PAYMENT CHANGE", "REPLY BLOCKED"],
    riskLevel: "blocked",
    riskFlags: [
      "Bank-detail change",
      "Known-domain mismatch",
      "Same-day payment pressure",
      "Unexpected attachment",
    ],
    facts: [
      "The sender requests new bank details be used.",
      "Invoice reference HLC-8841 is stated.",
      "The sender requests payment today.",
    ],
    missingInformation: ["Sender authority", "Invoice authenticity", "Supplier confirmation"],
    extracted: [
      { label: "Invoice", value: "HLC-8841", verified: false },
      { label: "Amount", value: "£8,420.00", verified: false },
      { label: "Due", value: "Today", verified: false },
      { label: "Reply-to", value: "halcyon-logistics.co", verified: false },
    ],
    requiredActions: [
      "Preserve message and attachment",
      "Verify through the supplier record",
      "Notify Security and Finance",
    ],
    attachments: [
      { name: "HLC-8841-remittance.html", type: "HTML", size: "96 KB", risk: "quarantined" },
    ],
    thread: [
      {
        id: "entry_03",
        sender: "Accounts Team",
        email: "accounts@halcyon-logistics.co",
        timestamp: "Today, 8:51 AM",
        direction: "inbound",
        body: [
          "Please disregard the bank account used for our previous invoices. Our details have changed and the replacement instructions are in the attached remittance file.",
          "Invoice HLC-8841 for £8,420 is due today. Please confirm payment by return.",
          "Accounts Team\nHalcyon Logistics",
        ],
      },
    ],
    auditReason:
      "Unverified bank-detail change combines a domain mismatch, unexpected HTML attachment and urgent payment request; reply and forwarding are blocked pending out-of-band verification.",
  },
  {
    id: "msg_01J72NQZ77",
    threadId: "thr_01J72NMMQA",
    sender: "Evelyn Carter",
    initials: "EC",
    email: "evelyn.carter@monarchandco.com",
    company: "Monarch & Co.",
    subject: "Duplicate subscription charge — refund needed",
    preview:
      "Our card appears to have been charged twice for the annual renewal. Please refund the duplicate £189…",
    receivedAt: "Yesterday",
    timestamp: "Yesterday, 4:36 PM",
    unread: false,
    priority: "high",
    category: "Refund request",
    secondaryCategories: ["Billing enquiry", "Complaint"],
    sentiment: "Frustrated",
    status: "needs-review",
    confidence: 91,
    relationship: "Active customer",
    summary:
      "Evelyn reports two annual-renewal card charges and requests a £189 refund. The billing system has not yet confirmed whether the charge is duplicated.",
    intent: "Receive a refund for a suspected duplicate charge",
    nextAction: "Billing must verify both transactions before any refund commitment.",
    assignee: "Billing review",
    labels: ["BILLING", "REFUND", "APPROVAL REQUIRED"],
    riskLevel: "review",
    riskFlags: ["Financial commitment", "Complaint"],
    facts: ["The customer states two charges occurred.", "The requested refund is £189."],
    missingInformation: ["Verified transaction IDs", "Duplicate charge confirmation"],
    extracted: [
      { label: "Amount", value: "£189.00", verified: true },
      { label: "Plan", value: "Annual renewal", verified: true },
      { label: "Account", value: "Monarch & Co.", verified: true },
    ],
    requiredActions: ["Verify both transactions", "Create refund approval if duplicated"],
    attachments: [],
    thread: [
      {
        id: "entry_04",
        sender: "Evelyn Carter",
        email: "evelyn.carter@monarchandco.com",
        timestamp: "Yesterday, 4:36 PM",
        direction: "inbound",
        body: [
          "Hi, our card appears to have been charged twice for the annual renewal. Please refund the duplicate £189 charge and let me know when it will arrive.",
          "Thanks,\nEvelyn",
        ],
      },
    ],
    draft: {
      subject: "Re: Duplicate subscription charge — refund needed",
      body: [
        "Hi Evelyn,",
        "I’m sorry for the concern caused by the two charges. I’ve recorded your request for the duplicate £189 charge to be reviewed.",
        "We need to verify the transactions before confirming a refund or timing. The billing team will review the account and follow up with the verified outcome.",
      ],
      signature: "Kind regards,\nNorthstar Billing",
    },
    auditReason:
      "Active customer requested a £189 refund; transaction duplication is not verified; financial and complaint approval rules require human review before sending or committing to an outcome.",
  },
  {
    id: "msg_01J72MZNN4",
    threadId: "thr_01J72MVKH7",
    sender: "Martin Cho",
    initials: "MC",
    email: "martin@emberdesk.io",
    company: "Emberdesk",
    subject: "SSO, SCIM and a 120-seat rollout",
    preview:
      "We are comparing platforms for a 120-person support team and need to understand your identity options…",
    receivedAt: "Yesterday",
    timestamp: "Yesterday, 2:08 PM",
    unread: false,
    priority: "normal",
    category: "Sales lead",
    secondaryCategories: ["Product question"],
    sentiment: "Neutral",
    status: "draft-ready",
    confidence: 93,
    relationship: "New prospect",
    summary:
      "Emberdesk is evaluating the product for a 120-seat support team and asks whether SSO and SCIM are supported. Their buying window is this quarter.",
    intent: "Confirm identity features and arrange a product call",
    nextAction: "Verify the approved SSO/SCIM product statement before replying.",
    assignee: "Sales triage",
    labels: ["SALES LEAD", "ENTERPRISE"],
    riskLevel: "none",
    riskFlags: [],
    facts: ["Prospect states 120 seats.", "Buying window is this quarter."],
    missingInformation: ["Identity provider", "Required provisioning workflow"],
    extracted: [
      { label: "Seats", value: "120", verified: true },
      { label: "Timeline", value: "This quarter", verified: true },
      { label: "Interest", value: "SSO and SCIM", verified: true },
    ],
    requiredActions: ["Check approved product matrix", "Request identity provider"],
    attachments: [],
    thread: [
      {
        id: "entry_05",
        sender: "Martin Cho",
        email: "martin@emberdesk.io",
        timestamp: "Yesterday, 2:08 PM",
        direction: "inbound",
        body: [
          "Hello, we’re comparing platforms for a 120-person support team and need to understand your SSO and SCIM options. We’re hoping to choose a vendor this quarter.",
          "Could someone confirm compatibility and arrange a short call?",
          "Martin",
        ],
      },
    ],
    draft: {
      subject: "Re: SSO, SCIM and a 120-seat rollout",
      body: [
        "Hi Martin,",
        "Thanks for sharing the context. A 120-seat support rollout and your identity requirements are both noted.",
        "I’m checking the approved SSO and SCIM compatibility details so we can give you an accurate answer. Which identity provider and provisioning workflow are you planning to use? Once confirmed, we can arrange a focused call with the right specialist.",
      ],
      signature: "Best,\nNorthstar Sales",
    },
    auditReason:
      "New enterprise prospect provided scope and timing; identity compatibility must be verified against approved product information; new-contact reply requires approval.",
  },
  {
    id: "msg_01J72M48TK",
    threadId: "thr_01J72M12SP",
    sender: "Priya Shah",
    initials: "PS",
    email: "priya.shah@bentonlegal.co.uk",
    company: "Benton Legal",
    subject: "Notice under clause 12.4 — response requested",
    preview:
      "We act for Aster Group. Please find attached formal notice under clause 12.4 of the agreement…",
    receivedAt: "Mon",
    timestamp: "Monday, 11:24 AM",
    unread: false,
    priority: "high",
    category: "Legal matter",
    secondaryCategories: ["Document received", "Deadline"],
    sentiment: "Neutral",
    status: "escalated",
    confidence: 98,
    relationship: "Legal representative",
    summary:
      "Benton Legal states that it acts for Aster Group and has attached a notice referencing clause 12.4. A written response is requested by 14 August.",
    intent: "Serve formal notice and obtain a written response",
    nextAction: "Legal should review the original notice and verify the response deadline.",
    assignee: "Legal review",
    labels: ["LEGAL REVIEW", "DEADLINE"],
    riskLevel: "blocked",
    riskFlags: ["Formal legal notice", "Stated response deadline"],
    facts: ["The email references clause 12.4.", "The email states a 14 August response date."],
    missingInformation: ["Authenticity of attached notice", "Applicable agreement version"],
    extracted: [
      { label: "Matter", value: "Clause 12.4 notice", verified: true },
      { label: "Party", value: "Aster Group", verified: true },
      { label: "Response", value: "14 August", verified: false },
    ],
    requiredActions: ["Preserve original", "Legal review", "Verify deadline"],
    attachments: [
      { name: "Aster-Group-Notice.pdf", type: "PDF", size: "2.4 MB", risk: "review" },
    ],
    thread: [
      {
        id: "entry_06",
        sender: "Priya Shah",
        email: "priya.shah@bentonlegal.co.uk",
        timestamp: "Monday, 11:24 AM",
        direction: "inbound",
        body: [
          "Dear Sirs,",
          "We act for Aster Group. Please find attached formal notice under clause 12.4 of the agreement. A written response is requested by 14 August.",
          "Yours faithfully,\nPriya Shah\nBenton Legal",
        ],
      },
    ],
    auditReason:
      "The message presents as a formal legal notice with a stated deadline; legal-category automation is prohibited and the original document requires human legal review.",
  },
  {
    id: "msg_01J72KTT10",
    threadId: "thr_01J72KPGA4",
    sender: "Product Weekly",
    initials: "PW",
    email: "digest@productweekly.example",
    company: "Product Weekly",
    subject: "This week in product operations",
    preview:
      "Seven practical ideas for reducing handoff time, plus the latest product operations jobs…",
    receivedAt: "Mon",
    timestamp: "Monday, 7:02 AM",
    unread: false,
    priority: "low",
    category: "Marketing newsletter",
    secondaryCategories: [],
    sentiment: "Neutral",
    status: "waiting",
    confidence: 96,
    relationship: "Marketing sender",
    summary:
      "Routine weekly product-operations newsletter with no requested response or operational deadline.",
    intent: "Share marketing content",
    nextAction: "No action. Eligible for archive after review.",
    assignee: "Unassigned",
    labels: ["NEWSLETTER", "LOW PRIORITY"],
    riskLevel: "none",
    riskFlags: [],
    facts: ["No response is requested."],
    missingInformation: [],
    extracted: [],
    requiredActions: [],
    attachments: [],
    thread: [
      {
        id: "entry_07",
        sender: "Product Weekly",
        email: "digest@productweekly.example",
        timestamp: "Monday, 7:02 AM",
        direction: "inbound",
        body: [
          "Seven practical ideas for reducing handoff time, plus the latest product operations jobs and events.",
        ],
      },
    ],
    auditReason:
      "Recognised marketing newsletter contains no request, deadline or operational notification; low priority and archive-eligible only after review in Safe Mode.",
  },
];

export const initialAuditEvents: AuditEvent[] = [
  {
    id: "audit_01",
    action: "Security escalation created",
    detail: "Payment-detail change on HLC-8841 routed to Security & Finance; reply blocked.",
    actor: "ClearInbox policy",
    time: "Today, 8:52 AM",
    tone: "danger",
  },
  {
    id: "audit_02",
    action: "Incident review created",
    detail: "Checkout outage marked critical and assigned to Incident response.",
    actor: "ClearInbox policy",
    time: "Today, 9:19 AM",
    tone: "warning",
  },
  {
    id: "audit_03",
    action: "Draft generated",
    detail: "Rollout reply created with pricing and ownership left explicitly unverified.",
    actor: "ClearInbox assistant",
    time: "Today, 9:43 AM",
    tone: "neutral",
  },
  {
    id: "audit_04",
    action: "Auto-label applied",
    detail: "SALES, HIGH VALUE and DRAFT READY applied to Maya Patel’s thread.",
    actor: "Rule SALES-UK-04",
    time: "Today, 9:43 AM",
    tone: "success",
  },
];

export const inboxCounts = {
  needsAttention: 12,
  approvals: 4,
  drafts: 7,
  sales: 5,
  support: 3,
  invoices: 2,
  security: 1,
};
